name: sphere
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - aiohttp=3.7.4.post0
  - async-timeout=3.0.1
  - attrs=21.4.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - cachetools=4.2.4
  - certifi=2024.8.30
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.11
  - click=8.0.3
  - cryptography=43.0.0
  - cudatoolkit=10.2.89
  - dataclasses=0.8
  - ffmpeg=4.3
  - flit-core=3.6.0
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.62.2
  - idna=3.3
  - importlib-metadata=4.10.1
  - intel-openmp=2021.4.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libabseil=20240116.2
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=4.25.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markdown=3.3.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.2.0
  - olefile=0.46
  - openh264=2.1.1
  - openssl=3.0.15
  - packaging=21.3
  - pandas=1.4.2
  - patsy=0.5.2
  - pillow=8.4.0
  - pip=21.2.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.3.0
  - pyopenssl=24.2.1
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.9.1
  - pytz=2022.1
  - pyu2f=0.1.5
  - re2=2022.04.01
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scipy=1.7.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.45.3
  - statsmodels=0.13.2
  - tabulate=0.8.9
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.14
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - urllib3=1.26.8
  - werkzeug=2.0.2
  - wheel=0.37.1
  - xz=5.4.6
  - yarl=1.6.3
  - zipp=3.7.0
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
      - astroid==3.2.4
      - dill==0.3.9
      - greenlet==1.1.2
      - isort==5.13.2
      - mccabe==0.7.0
      - msgpack==1.0.3
      - platformdirs==4.3.6
      - protobuf==3.20.1
      - pylint==3.2.7
      - pynvim==0.4.3
      - tensorboardx==2.4.1
      - tomli==2.1.0
      - tomlkit==0.13.2
      - torchmetrics==0.11.0
      - tqdm==4.65.0
      - typing-extensions==4.12.2
